---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/yourcode/comment/backend

    # Cloning the repository
    - name: Clone Repository
      command: |
        if [ -d "$DEPLOY_PATH/.git" ]; then
          cd $DEPLOY_PATH && git pull origin main
        else
          git clone https://github.com/CapstoneSIB-Comment/Backend.git $DEPLOY_PATH
        fi

    # Install dependencies
    - name: Install Dependencies
      command: |
        cd $DEPLOY_PATH
        npm install

    # Build application (if needed)
    - name: Build Application
      command: |
        cd $DEPLOY_PATH
        npm run build

    # Restart the application using PM2
    - name: Restart Application
      command: |
        cd $DEPLOY_PATH
        pm2 restart all || pm2 start app.js --name "comment-backend"

# Cron job for periodic updates
cron:
  tasks:
    - name: Scheduled Deployment
      command: /usr/local/bin/cpanel/scripts/cpanel.yaml
      schedule: '0 2 * * *' # Every day at 2 AM
